import { describe, it, expect } from 'vitest';
import { createDts } from '../core/createDts';

describe('createDts', () => {
  it('Common forms', () => {
    const name = 'createDts';
    const dts = createDts(name, {
      a: 'string',
      b: 1,
      c: true,
      d: { e: 'string' },
      f: '"string"',
      // prettier-ignore
      g: '\'string\'',
      // prettier-ignore
      h: 'string\'',
      i: "'a'|'b' |    'c'|",
      j: { k: "string | string'" },
    });

    expect(dts).toBe(
      getDtsBody(name, [
        'a: string',
        'b: 1',
        'c: true',
        'd: {\n      e: string\n    }',
        "f: 'string'",
        "g: 'string'",
        "h: 'string'",
        "i: 'a' | 'b' | 'c'",
        "j: {\n      k: string | 'string'\n    }",
      ]),
    );
  });

  it('With options', () => {
    const name = 'createDts';
    const dts = createDts(
      name,
      { a: 'string', b: undefined },
      { defaultType: 'unknown' },
    );

    expect(dts).toBe(getDtsBody(name, ['a: string', 'b: unknown']));
  });
});

const PREFIX = `// Generated by generate-dts
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
export {}
declare global {`;

const getDtsBody = (name: string, fieldList: string[]) => {
  const body = fieldList.map(field => `    ${field}`).join('\n');
  return `${PREFIX}
  export interface ${name} {
${body}
  }
}`;
};
