import { describe, it, expect, vi, afterEach } from 'vitest';
import { generateDts } from '..';
import { promises as fs } from 'node:fs';
import { resolve } from 'node:path';

const src = resolve(__dirname, '../');

describe('generateDts', () => {
  afterEach(() => {
    fs.unlink(resolve(src, './__tests__/GenerateDts.d.ts')).catch(() => {});
  });

  it('Common forms', async () => {
    const outputSpy = vi.fn();

    await generateDts({
      name: 'GenerateDts',
      directory: resolve(src, './__tests__'),
      parser: async () => ({ a: 'string', b: 1, c: '"1"' }),
      options: { output: outputSpy },
    });

    expect(outputSpy).toHaveBeenCalledWith(
      `// Generated by generate-dts
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
export {}
declare global {
  export interface GenerateDts {
    a: string
    b: 1
    c: '1'
  }
}`,
    );
  });

  it('Write to file', async () => {
    await generateDts({
      name: 'GenerateDts',
      directory: resolve(src, './__tests__'),
      parser: async () => ({ a: 'string', b: 1, c: '"1"' }),
    });

    const dts = (
      await fs.readFile(resolve(src, './__tests__/GenerateDts.d.ts'))
    ).toString();
    expect(dts).toBe(
      `// Generated by generate-dts
/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
export {}
declare global {
  export interface GenerateDts {
    a: string
    b: 1
    c: '1'
  }
}`,
    );
  });
});
