name: publish-sandbox

on:
  push:
    branches:
      - main

jobs:
  publish-sandbox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v4

      - uses: actions/cache@v4
        id: pnpm-cache
        with:
          path: demo/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('demo/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - if: steps.pnpm-cache.outputs.cache-hit != 'true'
        run: cd demo && pnpm install

      - run: cd demo && pnpm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./demo/dist
